#!/usr/bin/env bash

pause() {
    echo -e "\n$(printf -- '-%.0s' $(seq 1 $(tput cols)))\n"
    read -rp "Press RETURN to continue..."
}

declare -A COMMANDS
COMMANDS[1]="pip3 install -e portals/; pause"
COMMANDS[2]="python3 -m trainers.offline.train; pause"
COMMANDS[3]="python3 -m trainers.online.train; pause"
COMMANDS[4]="python3 -c 'from models.helper import revert_model; revert_model()'; pause"
COMMANDS[5]="uvicorn portals.api:app --host $(ip route get 1 | awk '{print $7}') --port 8001 --reload"
COMMANDS[6]="python3 -m portals.cli"

declare -A LABELS
LABELS[1]="Start Setup Portal"
LABELS[2]="Train Offline Model"
LABELS[3]="Train Online Model"
LABELS[4]="Revert Model Training"
LABELS[5]="Start API Portal"
LABELS[6]="Start CLI Portal"

while true; do
    
    clear
    echo

    for ((key=1; key<=${#COMMANDS[@]}; key++)); do
        echo "$key) ${LABELS[$key]}"
    done

    echo -e "q) Quit Developer Menu\n"
    
    read -p "Select Option: " choice

    if [[ "$choice" == "q" || "$choice" == "Q" ]]; then
        exit 0
    fi

    if [[ -n "${COMMANDS[$choice]}" ]]; then
        echo -e "\n$(printf -- '-%.0s' $(seq 1 $(tput cols)))\n"
        eval "${COMMANDS[$choice]}"
    else
        echo -e "\n$(printf -- '-%.0s' $(seq 1 $(tput cols)))\n"
        echo "Warning: You chose an invalid option."
        pause
    fi
    
done